services:
  web:
    image: my-web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"

