[global]
  sendAnonymousUsage = false

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = true

[entryPoints]
  [entryPoints.insecure]
    address = ":80"

